In [2]:
import pandas as pd
import numpy as np

In [3]:
p1 = pd.read_csv("pitch1_Sports2D_px_person00.trc")

In [11]:
from io import StringIO

In [19]:
data_frames = [pd.read_csv(StringIO(p1.iloc[i, 0]), sep="\t", header=None) for i in range(p1.shape[0])]

# Now concatenate all DataFrames into one
data_parsed = pd.concat(data_frames, ignore_index=True)

In [20]:
data_parsed

,0,1,2,3,4,5,6,7,8,9,...,58,59,60,61,62,63,64,65,66,67
0,DataRate,CameraRate,NumFrames,NumMarkers,Units,OrigDataRate,OrigDataStartFrame,OrigNumFrames,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,30.0,30.0,110,22,m,30.0,0,110,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Frame#,Time,Hip,NaN,NaN,RHip,NaN,NaN,RKnee,NaN,...,NaN,LShoulder,NaN,NaN,LElbow,NaN,NaN,LWrist,NaN,NaN
3,NaN,NaN,X1,Y1,Z1,X2,Y2,Z2,X3,Y3,...,Z19,X20,Y20,Z20,X21,Y21,Z21,X22,Y22,Z22
4,0,0.0,395.350546,354.816732,0.0,356.792224,363.199233,0.0,353.439254,509.051202,...,0.0,460.7327,173.758961,0.0,480.849976,270.993899,0.0,443.967975,326.316685,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,105,3.5,878.336697,397.772493,0.0,905.143076,402.981227,0.0,877.355422,512.548208,...,0.0,831.190997,265.645439,0.0,797.842885,345.681904,0.0,764.909924,399.1423,0.0
110,106,3.533333,878.884744,403.848756,0.0,904.928195,409.676122,0.0,872.122301,513.095022,...,0.0,833.239687,272.40953,0.0,797.95173,348.602745,0.0,757.026279,407.260155,0.0
111,107,3.566667,880.16692,404.075792,0.0,906.043815,410.073219,0.0,871.393515,509.236688,...,0.0,833.764298,272.059384,0.0,798.296527,346.032268,0.0,755.064976,410.185472,0.0
112,108,3.6,881.889766,397.311903,0.0,907.728148,403.459175,0.0,874.54135,502.831336,...,0.0,832.857502,264.795585,0.0,798.567222,337.178831,0.0,759.350886,405.026422,0.0
113,109,3.633333,883.95659,385.598449,0.0,909.744265,392.386224,0.0,879.878006,495.541805,...,0.0,831.025227,253.944737,0.0,798.452849,324.518539,0.0,767.231457,393.746862,0.0